
#import creds into variables
$cred_M365_Admin = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\M365_Admin.xml"
$Cred_CCP = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\CCP.xml"
$cred_CCR = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\CCR.xml"
$cred_CCS = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\CCS.xml"
$cred_CCT = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\CCT.xml"
$cred_CF  = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\CF.xml"
$cred_Altegrity = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\Altegrity.xml"
$Cred_CorpEddom = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\corpeddom.xml"
$cred_DR = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\DR.xml"
$cred_Eddom = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\eddom.xml"
$cred_EDP = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\EDP.xml"
$cred_KODMZ = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\KODMZ.xml"
$Cred_Koi = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\Koi.xml"
$cred_LDIAdmin = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\LDIAdmin.xml"
$Cred_LDINormal = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\LDINormal.xml"
$cred_LTDE = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\LTDE.xml"
$cred_LTEXT = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\LTEXT.xml"
$cred_Kroll = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\Kroll.xml"
$cred_LTY = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\LTY.xml"
$cred_LTZ = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\LTZ.xml"
$cred_OIR = Import-Clixml -Path "C:\Users\rui.ferreira\Creds\OIR.xml"